from enum import Enum


class EventType(Enum):

    REGISTER_TEST_STRATEGY = "REGISTER_TEST_STRATEGY"
    LIMIT_ORDER = "LIMIT_ORDER"
    TICK = "TICK"
    END_OF_CHART_DATA = "END_OF_CHART_DATA"
    NEW_CHART_DATA = "NEW_CHART_DATA"
    ERROR = "ERROR"
    OK = "OK"
